version: '3'
services:
  mongodb:
    image: mongo
    command: mongod
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  m4numbers:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      DATABASE_URI: "mongodb://mongodb:27017/database"
      REDIS_HOST: "redis"
      PROTECTED_HASH: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
      ADMIN_HASH: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
      COOKIES_DOMAIN: "192.168.99.100"
      COOKIES_DOMAIN_SEC: "192.168.99.100"
    ports:
      - "3000:3000"
